CREATE TABLE IF NOT EXISTS queue (
	mapKey STRING PRIMARY KEY,
	mapHash STRING DEFAULT NULL,
	mapTitle STRING DEFAULT "No Title",
	mapArtist STRING DEFAULT "Unknown Artist",
	mapAuthor STRING DEFAULT "Unknown Mapper",
	mapDuration INTEGER DEFAULT 0,
	requesterID INTEGER DEFAULT 0,
	flagIsModAdd BOOLEAN DEFAULT FALSE,
	flagModAddTargetID INTEGER DEFAULT 0,
	timeAdded INTEGER DEFAULT 0
);