const defaultConfig = {
	"enableBTTVGlobalEmotes": "true",
	"enableFFZBadges": "true",
	"chatMessageFont": "Manrope",
	"chatMaxBigEmotes": "10",
	"chatShadows": "true",
	"enable7TVBadges": "true",
	"chatAnimations": "true",
	"chatHighlightBackgroundColor": "#FFFFCCFF",
	"chatFadeHistory": "true",
	"chatAnimationsInDuration": "0.5",
	"chatAnimationsOutDuration": "0.75",
	"chatOutlineStyle": "solid",
	"chatFadeHistoryStep": "7",
	"chatOutlinesSize": "1",
	"enableFFZGlobalEmotes": "true",
	"enableFFZ": "true",
	"chatBackgroundColor": "#00000000",
	"chatMessageColor": "#ffffff",
	"enable7TVChannelEmotes": "true",
	"chatDefaultNameColor": "#aaaaaa",
	"chatMessageFontWeight": "700",
	"enable7TVGlobalEmotes": "true",
	"chatRemoveMessageDelay": "45",
	"enableBTTV": "true",
	"enableBTTVBadges": "true",
	"twitchClientSecret": "",
	"chatParseMarkdown": "true",
	"chatHideAccounts": "nightbot\nstreamlabs\nstreamelements\nkofistreambot\nblerp\nsery_bot\ncommanderroot",
	"twitchChannel": "",
	"chatOutlinesColor": "#ffffff",
	"chatMessageFontSize": "16",
	"chatOutlinesFilter": "true",
	"twitchClientID": "",
	"chatNameFontWeight": "900",
	"enable7TV": "true",
	"chatHideCommands": "true",
	"chatCommandCharacter": "!",
	"chatBigEmoteSize": "48",
	"enable7TVUserPaints": "true",
	"chatNameFontSize": "16",
	"chatBlockBorderRadius": "0",
	"chatShowBigEmotes": "true",
	"chatBlockPaddingVertical": "18",
	"chatBlockPaddingHorizontal": "18",
	"enableFFZChannelEmotes": "true",
	"chatOutlines": "false",
	"enableBTTVChannelEmotes": "true",
	"chatNameFont": "Manrope",
	"chatBlockIndividualPaddingVertical": "0",
	"chatBlockIndividualPaddingHorizontal": "0",
	"debugRawMessages": "false",
	"chatCornerAlignment": "bottom,left",
	"chatMessageLineHeight": "30",
	"enableAvatars": "true",
	"avatarAllowedModerators": "true",
	"avatarAllowedVIPs": "true",
	"avatarAllowedSubscribers": "true",
	"avatarAllowedTurbo": "true",
	"avatarAllowedPrime": "false",
	"avatarAllowedArtist": "true",
	"avatarAllowedPartner": "false",
	"avatarAllowedStaff": "false",
	"avatarAllowedEveryone": "false",
	"avatarAllowedIncludeBits": "true",
	"avatarAllowedBitsMinimum": "1000",
	"enablePronouns": "true",
	"avatarSize": "34",
	"avatarShape": "squircle",
	"chatDefaultNameColorForced": "false",
	"chatMessageUserInfoElementSpacing": "14",
	"chatAnimationInName": "slideInBottomKF",
	"chatAnimationOutName": "slideOutLeftKF",
	"overlayShadowColor": "#000000",
	"overlayShadowXOffset": "0",
	"overlayShadowYOffset": "1",
	"overlayShadowBlurRadius": "2",
	"overlayOutlineColor": "#00000073",
	"overlayOutlineSize": "1",
	"pronounsAeAer": "Ae / Aer",
	"pronounsAny": "Any",
	"pronounsEEm": "E / Em",
	"pronounsFaeFaer": "Fae / Faer",
	"pronounsHeHim": "He / Him",
	"pronounsHeShe": "He / She",
	"pronounsHeThem": "He / They",
	"pronounsItIts": "It / Its",
	"pronounsOther": "Other",
	"pronounsPerPer": "Per / Per",
	"pronounsSheHer": "She / Her",
	"pronounsSheThem": "She / They",
	"pronounsTheyThem": "They / Them",
	"pronounsVeVer": "Ve / Ver",
	"pronounsXeXem": "Xe / Xem",
	"pronounsZieHir": "Zie / Hir",
	"chatAnimationInOriginPoint": "center center",
	"chatAnimationOutOriginPoint": "left center",
	"chatAnimationInTimingFunction": "EaseInOutCubic",
	"chatAnimationOutTimingFunction": "EaseInBack",
	"enableTwitchBadges": "true",
	"enableTwitchRoleBadges": "true",
	"enableTwitchGameBadges": "true",
	"enableTwitchPartnerBadges": "true",
	"enableTwitchBitsBadges": "true",
	"enableTwitchSubGiftsBadges": "true",
	"enableTwitchLeaderboardBadges": "true",
	"enableTwitchFounderBadges": "true",
	"enableTwitchStaffBadges": "true",
	"enableTwitchMomentsBadges": "false",
	"enableTwitchStatusBadges": "false",
	"enableTwitchPredictionsBadges": "true",
	"enableTwitchPrimeGamingBadges": "true",
	"enableTwitchTurboBadges": "true",
	"enableTwitchSubscriberBadges": "true",
	"enableTwitchConBadges": "true",
	"enableTwitchCharityBadges": "true",
	"enableTwitchHypeTrainBadges": "true",
	"badgeBorderRadius": "4",
	"badgeSpacing": "2",
	"badgeSize": "28",
	"chatNameFontWeightExtra": "1.2",
	"chatNameUsesGradient": "true",
	"chatDefaultNameColorSecondary": "#FFFFFF",
	"chatNameGradientAngle": "170",
	"chatNameLetterSpacing": "1",
	"messageLetterSpacing": "0",
	"pronounsColor": "#808080",
	"pronounsUsesGradient": "true",
	"pronounsColorSecondary": "#FFFFFF",
	"pronounsGradientAngle": "170",
	"pronounsFont": "Manrope",
	"pronounsFontSize": "12",
	"pronounsFontWeight": "900",
	"pronounsFontWeightExtra": "0.5",
	"pronounsLetterSpacing": "0",
	"chatNameTransform": "uppercase",
	"messageTransform": "none",
	"pronounsTransform": "uppercase",
	"enableFlags": "true",
	"flagsBorderRadius": "4",
	"flagsSize": "22",
	"flagsSpacing": "2",
	"chatBlockSpacing": "20",
	"messageBoldAmount": "1.25",
	"chatShowCommonEmotes": "true",
	"maxFlagCount": "6",
	"enableMessageTimestamps": "false",
	"timestampUsesGradient": "true",
	"timestampColor": "#808080",
	"timestampColorSecondary": "#FFFFFF",
	"timestampGradientAngle": "170",
	"timestampFont": "Manrope",
	"timestampFontSize": "12",
	"timestampFontWeight": "900",
	"timestampFontWeightExtra": "0.5",
	"timestampLetterSpacing": "0",
	"timestampPadding": "10",
	"timestampFormat": "H:mm:ss",
	"timestampTracksUptime": "false",
	"chatBlurHistory": "false",
	"chatBlurHistoryStep": "0.2",
	"chatHistoryStartAfter": "3",
	"hideTimestampsOnBigEmotes": "true",
	"chatMessageUserInfoBackgroundColor": "#00000000",
	"chatMessageUserInfoElementPaddingVertical": "0",
	"chatMessageUserInfoElementPaddingHorizontal": "0",
	"chatMessageUserInfoElementBorderRadius": "0",
	"chatBlockWidth": "-webkit-fill-available",
	"allowUserCustomizations": "true",
	"avatarAllowedAffiliates": "false",
	"applyBorderRadiusToSubBadges": "false",
	"chatOutlinesReflectUserColor": "false",
	"chatOutlinesUserColorAmount": "50",
	"chatBackgroundReflectUserColor": "false",
	"chatBackgroundUserColorAmount": "50",
	"nameColorMinBrightness": "30",
	"nameColorMaxBrightness": "100",
	"ensureNameColorsAreBrightEnough": "true",
	"chatMessageUserInfoBackgroundReflectUserColor": "false",
	"chatMessageUserInfoBackgroundUserColorAmount": "50",
	"chatMessageUserInfoOutlines": "false",
	"chatMessageUserInfoOutlinesColor": "#ffffff",
	"chatMessageUserInfoOutlinesReflectUserColor": "false",
	"chatMessageUserInfoOutlinesUserColorAmount": "100",
	"chatMessageUserInfoOutlinesSize": "1",
	"chatMessageUserInfoOutlineStyle": "solid",
	"pronounsReflectUserColor": "false",
	"pronounsUserColorAmount": "50",
	"chatMessageReflectUserColor": "false",
	"chatMessageUserColorAmount": "10",
	"chatMessageUserInfoBottomMargin": "4",
	"chatMessagesHardCap": "200",
	"debugFreezeChat": "false",
	"enableEmotes": "true",
	"emotesParseToImage": "true",
	"emotesBorderRadius": "0",
	"chatBigEmoteMargin": "0",
	"chatBigEmoteMarginVertical": "4",
	"overlayForceWidth": "false",
	"overlayWidth": "700",
	"chatMessageEnableSeparators": "false",
	"chatMessageSeparatorColor": "#ffffff20",
	"chatMessageSeparatorWidth": "1",
	"chatMessageSeparatorSpacing": "0",
	"chatMessageSeparatorStyle": "solid",
	"hideDefaultAvatars": "true",
	"avatarAllowedIncludeGifts": "true",
	"avatarAllowedGiftsMinimum": "5",
	"chatHighlightGlowRadius": "3",
	"chatShowCheermotes": "true",
	"chatShowCheermotesColor": "true",
	"chatShowCheermotesAnimated": "true"
};

for(let setting in defaultConfig) {
	if(!localStorage.getItem(`setting_${setting}`)) {
		console.log(`saving default value for setting ${setting}`);
		localStorage.setItem(`setting_${setting}`, defaultConfig[setting]);
	} else {
		if(setting.indexOf("FFZ") === -1 && setting.indexOf("7TV") === -1 && setting.indexOf("BTTV") === -1)
		updateSetting(`setting_${setting}`, localStorage.getItem(`setting_${setting}`));
	}
}